CREATE SCHEMA IF NOT EXISTS DBO;


DROP TABLE IF EXISTS DBO.PROFILE CASCADE;

CREATE TABLE DBO.PROFILE (
  PROFILE_ID INT PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  PHONE VARCHAR(12) NOT NULL,
  EMAIL VARCHAR(20) NULL
);


DROP TABLE IF EXISTS DBO.PRODUCT CASCADE;

CREATE TABLE DBO.PRODUCT (
  PRDT_ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(1200) NULL,
  RATE DOUBLE NOT NULL
);


DROP TABLE IF EXISTS DBO.CART CASCADE;

CREATE TABLE DBO.CART (
  CART_ID INT PRIMARY KEY AUTO_INCREMENT,
  PROFILE_ID INT,
  PRDT_ID INT,
  QUANTITY INT NOT NULL,
  TOTAL DOUBLE NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  UPDATED_DATE TIMESTAMP  NULL
);

ALTER TABLE DBO.CART
  ADD CONSTRAINT CART_PRFL_FK FOREIGN KEY (PROFILE_ID)
  REFERENCES DBO.PROFILE (PROFILE_ID);
ALTER TABLE DBO.CART
  ADD CONSTRAINT CART_PRDT_FK FOREIGN KEY (PRDT_ID)
  REFERENCES DBO.PRODUCT (PRDT_ID);


DROP TABLE IF EXISTS DBO.ORDERS CASCADE;

CREATE TABLE DBO.ORDERS (
  ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
  CART_ID INT NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL
);