CREATE SCHEMA IF NOT EXISTS dbo;

DROP TABLE IF EXISTS dbo.PROFILE CASCADE;

CREATE TABLE dbo.PROFILE (
  PROFILE_ID INT auto_increment,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  PHONE VARCHAR(12) NOT NULL,
  EMAIL VARCHAR(20) NULL
);

ALTER TABLE dbo.PROFILE
  ADD PRIMARY KEY (PROFILE_ID) ;

DROP TABLE IF EXISTS dbo.PRODUCT CASCADE;

CREATE TABLE dbo.PRODUCT (
  PRDT_ID INT auto_increment,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(1200) NULL,
  RATE DOUBLE NOT NULL
);

ALTER TABLE dbo.PRODUCT
  ADD PRIMARY KEY (PRDT_ID) ;


DROP TABLE IF EXISTS dbo.CART CASCADE;

CREATE TABLE dbo.CART (
  CART_ID INT auto_increment,
  PROFILE_ID INT,
  PRDT_ID INT,
  QUANTITY INT NOT NULL,
  TOTAL DOUBLE NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  UPDATED_DATE TIMESTAMP  NULL,
  PRIMARY KEY (CART_ID)
);

--alter table dbo.CART
--  add primary key (CART_ID) ;
alter table dbo.CART
  add constraint CART_PRFL_FK foreign key (PROFILE_ID)
  references dbo.PROFILE (PROFILE_ID);
alter table dbo.CART
  add constraint CART_PRDT_FK foreign key (PRDT_ID)
  references dbo.PRODUCT (PRDT_ID);

--DROP TABLE IF EXISTS dbo.ORDERS CASCADE;
--
--CREATE TABLE dbo.ORDERS (
--  ORDER_ID INT auto_increment,
--  CART_ID INT NOT NULL,
--  CREATED_DATE TIMESTAMP NOT NULL,
--  PRIMARY KEY (ORDER_ID)
--);
--
--alter table dbo.ORDERS
--  add constraint ORD_CART_FK foreign key (CART_ID)
--  references dbo.CART (CART_ID);